config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "home#index"
  resources :users

  resources :humsters do
   resources :comments,only:[:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :cotegory_relations, dependent: :destroy
	has_many :humsters,through: :category_relations, dependent: :destroy
end

app/models/category_relation.rb
class CategoryRelation < ApplicationRecord
  belongs_to :humster
  belongs_to :category
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :humster

  validates :content,presence: true
  
end

app/models/humster.rb
class Humster < ApplicationRecord
	belongs_to :user
    has_one_attached :image

    with_options presence: true do
    validates :title
    validates :body
  end

    has_many :comments, dependent: :destroy

    has_many :category_relations, dependent: :destroy
    has_many :categories,through: :category_relations, dependent: :destroy


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :humsters, dependent: :destroy

  validates :username,presence: true
  
  has_many :comments,dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  

  protected

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create

    @humster = Humster.find(params[:humster_id])
    @comment = @humster.comments.build(comment_params)
    @comment.user_id = current_user.id


    if @comment.save
     redirect_back(fallback_location: root_path)
    else

     redirect_back(fallback_location: root_path)
    end

  end

  

  private
  def comment_params
    params.require(:comment).permit(:content,:humster_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end
end

app/controllers/humsters_controller.rb
class HumstersController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  PER=6

  def index
  	@humsters=Humster.page(params[:page]).per(PER)
  end

  def show
  	@humster=Humster.find(params[:id])

    @comments = @humster.comments.includes(:user).page(params[:page]).per(PER)
    @comment=@humster.comments.build(user_id: current_user.id) if current_user
  end

  def new
  	@humster=Humster.new
  end

  def create
  	@humster=Humster.new(humster_params)
  	@humster.user_id=current_user.id
  	if @humster.save
  	redirect_to humster_path(@humster),notice:"投稿に成功しました"
    else
      render :new
    end
  end

  def edit
  	@humster=Humster.find(params[:id])
    if @humster.user != current_user
      redirect_to humsters_path,alert:"不正アクセスです"
    end
  end

  def update
  	@humster=Humster.find(params[:id])
  	if @humster.update(humster_params)
  	redirect_to humster_path(@humster)
    else
      render :edit
    end
  end

  def destroy
    humster=Humster.find(params[:id])
    humster.destroy
    redirect_to humsters_path
    
  end

  private
  def humster_params
  	params.require(:humster).permit(:title,:body,:image,category_ids: [])
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  PER=12
  # 12つめで次のページ

  def index
  	@users=User.page(params[:page]).per(PER)
  end

  def show
  	@user=User.find(params[:id])

  end

  def edit
  	@user=User.find(params[:id])
    if @user != current_user
      redirect_to users_path,alert:"不正なアクセスです"
    end
  end

  def update
  	@user=User.find(params[:id])
  	if @user.update(user_params)
  	redirect_to user_path(@user),notice: "ユーザー情報を更新しました。"
    
    else
    render :edit
    end
  end

  def destroy
    user = User.find(params[:id]) 
    user.destroy 
    redirect_to users_path
  end



  private
  def user_params
  	params.require(:user).permit(:username,:email,:profile,:profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/humsters_helper.rb
module HumstersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div id="form-main">
  <div id="form-div">
    
      
      <div class="column is-6">
        <section class="flame">

          <h2 class="text">Humster House</h2>
          <br>
          <div class="login_new">
          <%= link_to "ログイン", new_user_session_path, class: "button is-black is-fullwidth" %>
          <br>
          <%= link_to "新規登録", new_user_registration_path, class: "button is-black is-fullwidth" %>
          </div>
        </section>
      </div>

  
  </div>
</div>







 

app/views/humsters/edit.html.erb
<section class="hero is-white">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        募集詳細編集<hr>
      </h1>
    </div>
  </div>
</section>

<% if @humster.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@humster.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @humster.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @humster do |f| %>
          <div class="field">
            <%= f.label :title, "ハムスターの種類", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "詳細", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.file_field :image, class: "input" %>
          </div>

          <%= f.submit '更新', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/humsters/index.html.erb
<section class="hero is-white">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        募集詳細一覧<hr>
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @humsters.each do |humster| %>
        <div class="column is-4">
          <div class="card">
          <div class="card-content">
            <div class="card-image">
              
                <%= link_to humster_path(humster) do %>

                <figure class="image is-4by3">
                <% if humster.image.attached? %>
                <%= image_tag humster.image %>
                
                </figure>

                <%else%>
                <figure class="default-image">
                <%= image_tag 'default.png'%>
                </figure>
                <% end %>
                <% end %>
              
            </div>
          </div>

          <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="post-title"><%=link_to humster.user.username, user_path(humster.user) %>
                  さんの募集</div>
                </div>
              </div>

              <div class="content">
                <time><%= humster.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <%= paginate @humsters %>
    </div>
  </div>
</section>

app/views/humsters/new.html.erb
<section class="hero is-white">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        新しく募集をする<hr>
      </h1>
    </div>
  </div>
</section>


<% if @humster.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@humster.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @humster.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @humster do |f| %>
          <div class="field">
            <%= f.label :title, "募集タイトル", class: "label"%>
            <%= f.text_field :title, class: "input" ,:placeholder => "例:一身上の都合で飼えなくなりました"%>
          </div>

          <div class="field">
            <%= f.label :body, "詳細", class: "label" %>
            <%= f.text_area :body, class: "textarea",:placeholder => "生まれた日,健康状態,性格,性別,引き渡し方法,ワクチン有無など..." %>
          </div>

          <div class="field">

            <%= f.label :category,"カテゴリー",class: "label"%>
            <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %> 
            <%= category.label do %>
            <%= category.check_box %>
            <%= category.text %>
            <% end %>
            <% end %>
            
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.file_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/humsters/show.html.erb
<section class="hero is-white">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        募集詳細<hr>
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">

              <% if @humster.image.attached? %>
              <%= image_tag @humster.image %>
              <%else%>
              <%= image_tag 'default.png'%>
              <% end %>


              
            </figure>
          </div>
          <div class="card-content">
            
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <td><h3>ハムスターの種類</h3><br>
                  <%= @humster.title %></td>
                </tr>

                <tr>
                  <td align="left"><h3>カテゴリー</h3><br>
                  <% @humster.categories.each do |category| %>
  　　　　　　　　　<%= category.name %>
                  <% end %>
　　　　　　　　　　</td>
                </tr>
                
                <tr>
                  <td><h3>募集詳細</h3><br>
                    <%= simple_format @humster.body %></td>
                </tr>

                
              </table>

              <% if @humster.user.id == current_user.id %>
                <%= link_to "編集画面へ", edit_humster_path(@humster), class: "button is-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-4">

        <article class="panel is-black">
          <p class="panel-heading">
            By <%= @humster.user.username %>
          </p>
          <div class="panel-block">
            <p class="control">
              <%= @humster.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@humster.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @humster.user.username %> さんのページへ
          <% end %>
        </article>

        <div>
        
        <h2 class="comment-title"> この募集にコメントをする</h2>

        <%= form_with model: [@humster, @comment],local: true do |f| %>

        <div class="field">
        <%= f.text_area :content %>
        
        </div>

        <%= f.submit 'コメントする',class: "button is-success" %>

        <% end %>


        <div class="content">
          <h2 class="comment-title">コメント一覧</h2>
          <table class="table is-narrow">

        <% if @comments.any? %>

        <% @comments.each do |comment| %>
         <tr>
          <td>
            ユーザ名：<%= comment.user.username %>
            <br>
            コメント内容：<%= comment.content %>
          </td>
         </tr>
        <% end %>
        <% end %>

          </table>
        </div>

        <%= paginate @comments%>



        </div>

      </div>
      
    </div>
  </div>
</section>

app/views/layouts/_footer.html.erb
<footer class="footer">
   <div class="container">
     <div class="content has-text-centered">
       2020 ©Kousai Sasaki
     </div>
   </div>
</footer>

app/views/layouts/_header.html.erb
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>




    <nav class="navbar is-dark">

      <div class="navbar-brand">
        <a class="navbar-item logo" href="/">
        <h1 class="title is-4">Humster House</h1>
        </a>
        


        <div class="navbar-burger burger " data-target="navbarMenuHeroC" id="nav-drawer">
          <input id="nav-input" type="checkbox" class="nav-unshown">
          <label id="nav-open" for="nav-input"><span></span></label>
          <label class="nav-unshown" id="nav-close" for="nav-input"></label>
         <div id="nav-content">
         <ul class="nav navbar-nav navbar-right">
           <% if user_signed_in?%>

             <li><%= link_to '募集一覧',humsters_path
              %></li>
              <hr>
              <li><%= link_to "新しく募集をする", new_humster_path %></li>
              <hr>
              <li><%= link_to "ユーザーの一覧", users_path %></li>
              <hr>
              <li><%= link_to "マイページ", user_path(current_user) %></li>
              <hr>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete%></li>

            <% else %>
             <li>
              <%= link_to '募集一覧',humsters_path
              %>
             </li>
             
             <hr>
             <li>
               <%= link_to "ユーザーの一覧", users_path %>
             </li>
             
             <hr>
             <li>
               <%= link_to "ログイン", new_user_session_path %>
             </li>
             
             <hr>
             <li>
               <%= link_to "新規登録", new_user_registration_path %>
             </li>



           <%end%>
         </div>

        </div>

      </div>



      <% if user_signed_in? %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-end">

          <div class="navbar-item">
            <%= link_to "募集一覧", humsters_path, class: "navbar-item " %>
          </div>
          
          <div class="navbar-item">
            <%= link_to "新しく募集する", new_humster_path, class: "navbar-item" %>
          </div>

          <div class="navbar-item">
          <%= link_to "ユーザーの一覧", users_path, class: "navbar-item " %>
          </div>

          <div class="navbar-item">
          <%= link_to "マイページ", user_path(current_user), class: "navbar-item " %>
          </div>

          <div class="navbar-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "navbar-item " %>
          </div>

          </div>
        </div>
          

        
      <% else %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-end">

          <div class="navbar-item">
            <%= link_to "募集一覧", humsters_path, class: "navbar-item " %>
          </div>
          
          <div class="navbar-item">
            <%= link_to "ユーザーの一覧", users_path, class: "navbar-item " %>
          </div>
          
          <div class="navbar-item">
            <%= link_to "ログイン", new_user_session_path, class: "navbar-item " %>
          </div>

          <div class="navbar-item">
          <%= link_to "新規登録", new_user_registration_path, class: "navbar-item " %>
          </div>

          </div>
        </div>

          
        
      <% end %>

    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Humster House</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0, user-scalable=yes">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    
  </head>

  <body>
    
    <%= render "layouts/header"%>
    <%= yield %>
    <%= render "layouts/footer"%>
    
  </body>
</html>

app/views/users/edit.html.erb
<section class="hero is-white">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集<hr>
      </h1>
    </div>
  </div>
</section>


<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.file_field :profile_image, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero is-white">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        利用ユーザー<hr>
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                
                <%= link_to user_path(user) do %>
                <figure class="image">
                <% if user.profile_image.attached? %>
                <%= image_tag user.profile_image
                 %>
                </figure>

                <%else%>
                <figure class="default-image">
                <%= image_tag 'default.png'
                 %>
                </figure>
                <% end %>
                <% end %>
                

              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="post-title"><%=link_to user.username, user_path(user) %></div>
                </div>
              </div>
              <div class="content">
               投稿数:<%= user.humsters.count %>
              </div>
            </div>
          </div>
        </div>
      <% end %>

      <%= paginate @users %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero is-white">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイページ<hr>
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-6">


            <% if @user.profile_image.attached? %>
            <figure class="image is-200x200"  style="margin-left: auto; margin-right: auto;">
            <%= image_tag @user.profile_image %>
            </figure>

            <else>
            <% else %>
            <figure class="image is-200x200"  style="margin-left: auto; margin-right: auto;">
            <%= image_tag 'default.png'%>
            </figure>
            <% end %>


          </div>

          <div class="column is-6">

            <div class="content">

                <table class="table full-width">

                <tr>
                <td><h4>ユーザー名</h4>
                  <%= @user.username %></td>
                </tr>
              
                <tr>
                  <td class="profile-name">
                    <h4>メールアドレス</h4>
                      <%= @user.email %></td>
                </tr>
                
                <tr>  
                  
                  <td class="profile-name"><h4>ユーザー情報</h4>
                    <%= simple_format @user.profile %></td>
                <tr>

                </table>
              

            </div> 
                
          </div>



        </div>
      </div>
    </div>

    <% if @user.id == current_user.id %>

    <div class="buttons">
        <span class="user-edit"><%= link_to "ユーザーの編集", edit_user_path(@user), class: "button is-primary" %></span>
        <span class="user-delete"> <%= link_to "ユーザーの削除", user_path(@user), class: "button is-danger",method: :delete,data: {confirm:'投稿も消えてしまいますが、削除してもよろしいですか？'} %></span>

    <% end %> 

    </div>


  </div>
</section>


<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.humsters.each do |humster| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to humster_path(humster) do %>

                  <% if humster.image.attached? %>
                  <%= image_tag humster.image %>
                  <%else%>
                  <%= image_tag 'default.png'%>
                  <% end %>

                <% end %>
              </figure>
            </div>

            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to humster_path(humster), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    この募集を見る
                  <% end %>

                  <% if @user.id == current_user.id %>

                    <%= link_to edit_humster_path(humster), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      この募集を編集する
                    <% end %>

                    <%= link_to humster_path(humster), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      この募集を削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= humster.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>